version: '3.8'

services:
  web:
    build:
      context: app
    command: >
      sh -c "python manage.py migrate && python manage.py appcreatesuperuser && gunicorn config.wsgi:application -w 2 -b :8000 --reload"
    volumes:
      - ./app/static:/home/app/web/static
      - ./app/media:/home/app/web/media
      - .:/code
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
    restart: always
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    volumes:
      - ./app/static:/static
      - ./app/media:/media
      - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - 80:80
    depends_on:
      - web
  redis:
    image: redis:alpine

  celery:
    restart: always
    build:
      context: app
    command: celery -A config worker -l info
    volumes:
      - ./app:/app
    env_file:
      - ./.env.prod
    depends_on:
      - db
      - redis
      - web

volumes:
  postgres_data:
