# Generated by Django 3.1.4 on 2022-04-26 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belonging', models.CharField(choices=[(1, 'channel'), (2, 'user')], max_length=100)),
                ('type', models.CharField(choices=[(1, 'period'), (2, 'views'), (3, 'subs'), (4, 'videos'), (5, 'special')], max_length=100)),
                ('amount', models.CharField(max_length=100)),
                ('image', models.ImageField(help_text='Squared image. Optimal size is 256x256', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.CharField(max_length=50, unique=True)),
                ('desc', models.TextField(blank=True, max_length=500, null=True)),
                ('max_channels', models.IntegerField(default=1)),
                ('check_frequency', models.IntegerField(default=1)),
                ('check_time', models.IntegerField(default=7)),
                ('check_frequency_after_check_time', models.IntegerField(default=7)),
                ('check_time_2', models.IntegerField(default=28)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('surname', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('phone', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('email_proved', models.BooleanField(default=False)),
                ('telegram_chat', models.IntegerField(default=-1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rewards', models.ManyToManyField(to='users.Reward')),
                ('subscription', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='users.subscription')),
            ],
        ),
    ]
