# Generated by Django 3.1.4 on 2022-04-27 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220426_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='special_color',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
