# Generated by Django 3.1.4 on 2022-04-27 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_subscription_special_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='special_color',
            field=models.CharField(default='000', max_length=10),
        ),
    ]
