# Generated by Django 3.1.4 on 2022-04-27 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20220428_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='belonging',
            field=models.IntegerField(choices=[(1, 'channel'), (2, 'user')]),
        ),
        migrations.AlterField(
            model_name='reward',
            name='type',
            field=models.IntegerField(choices=[(1, 'period'), (2, 'views'), (3, 'subs'), (4, 'videos'), (5, 'special')]),
        ),
    ]
