# Generated by Django 3.1.4 on 2022-04-27 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20220428_0047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='client',
            name='staff',
        ),
        migrations.AddField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
