# Generated by Django 3.1.4 on 2022-04-27 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_client_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
