# Generated by Django 3.1.4 on 2022-04-27 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20220428_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='subscription',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.subscription'),
        ),
    ]
