# Generated by Django 3.1.4 on 2022-04-27 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20220428_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='rewards',
            field=models.ManyToManyField(blank=True, default=None, to='users.Reward'),
        ),
    ]
