# Generated by Django 3.1.4 on 2022-04-27 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_remove_client_rewards'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='rewards',
            field=models.ManyToManyField(blank=True, default=None, to='users.Reward'),
        ),
    ]
