# Generated by Django 3.1.4 on 2022-04-27 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_remove_client_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.subscription'),
        ),
    ]
