# Generated by Django 3.1.4 on 2022-05-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_client_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='last_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reward',
            name='image',
            field=models.ImageField(help_text='Квадратное изображение. Оптимальный размер - 256x256', upload_to='rewards/'),
        ),
    ]
