# Generated by Django 3.1.7 on 2021-03-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20210301_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chat',
            field=models.IntegerField(default=0),
        ),
    ]
