# Generated by Django 3.1.7 on 2021-03-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_completetask_question_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='playlist_id',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
