# Generated by Django 3.1.7 on 2021-03-11 07:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0013_auto_20210311_0649'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='completetask',
            options={'verbose_name': 'Задание на проверку', 'verbose_name_plural': 'Задания на проверку'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Частый вопрос', 'verbose_name_plural': 'Частые вопросы'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Задание для пользователям', 'verbose_name_plural': 'Задания для пользователя'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['rating'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='task',
            name='datetime',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата публикации вопроса'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Задание'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_rating',
            field=models.IntegerField(default=2, verbose_name='Количество рейтинга за выполнение'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_text',
            field=models.TextField(verbose_name='Текст задания'),
        ),
        migrations.AlterField(
            model_name='user',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bot.category', verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='user',
            name='chat',
            field=models.IntegerField(default=0, unique=True, verbose_name='идентификатор чата'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=40, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='playlist_id',
            field=models.CharField(blank=True, max_length=200, verbose_name='плейлист youtube канала'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='рейтинг'),
        ),
        migrations.AlterField(
            model_name='user',
            name='target',
            field=models.TextField(verbose_name='цель'),
        ),
        migrations.AlterField(
            model_name='user',
            name='youtube',
            field=models.CharField(max_length=200, verbose_name='идентификатор youtube канала'),
        ),
    ]
