# Generated by Django 3.1.7 on 2021-03-11 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0014_auto_20210311_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completetask',
            name='answer',
            field=models.TextField(verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='completetask',
            name='comment',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Ваш комментарий'),
        ),
        migrations.AlterField(
            model_name='completetask',
            name='status',
            field=models.CharField(choices=[('CH', 'Задание на проверке'), ('CM', 'Задание выполнено'), ('FL', 'Задание провалено')], default='CH', max_length=2, verbose_name='Статус задания'),
        ),
        migrations.AlterField(
            model_name='completetask',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bot.task', verbose_name='Задание'),
        ),
        migrations.AlterField(
            model_name='completetask',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bot.user', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.TextField(verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=200, verbose_name='Вопрос'),
        ),
    ]
