# Generated by Django 3.1.7 on 2021-03-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0015_auto_20210311_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_publish',
            field=models.BooleanField(default=False),
        ),
    ]
