# Generated by Django 3.1.7 on 2021-03-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0017_completetask_okey'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='last_message',
            field=models.TextField(default=''),
        ),
    ]
