# Generated by Django 3.1.7 on 2021-03-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0018_task_last_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='last_message',
        ),
        migrations.AddField(
            model_name='user',
            name='last_message',
            field=models.TextField(default=''),
        ),
    ]
