# Generated by Django 3.1.7 on 2021-03-23 15:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0022_auto_20210314_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_from_last_message', models.TimeField(default=datetime.datetime(2021, 3, 23, 18, 27, 36, 474486))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.user')),
            ],
        ),
    ]
