# Generated by Django 3.1.7 on 2021-10-30 12:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0025_auto_20210324_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertime',
            name='time_from_last_message',
            field=models.TimeField(default=datetime.datetime(2021, 10, 30, 15, 2, 35, 24394)),
        ),
    ]
