# Generated by Django 3.1.7 on 2021-03-02 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_completetask_question_task'),
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Channels',
            new_name='Channel',
        ),
    ]
