# Generated by Django 3.1.4 on 2022-04-26 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('channels', '0007_auto_20210311_2134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Niche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.TextField()),
                ('youtube', models.CharField(max_length=200, verbose_name='Идентификатор youtube канала')),
                ('playlist_id', models.CharField(blank=True, max_length=200, verbose_name='плейлист youtube канала')),
                ('subs_day', models.IntegerField(default=0, verbose_name='подписчики за день')),
                ('subs_week', models.IntegerField(default=0, verbose_name='подписчики за неделю')),
                ('subs_month', models.IntegerField(default=0, verbose_name='подписчики за месяц')),
                ('subs_quarter', models.IntegerField(default=0, verbose_name='подписчики за квартал')),
                ('views_day', models.IntegerField(default=0, verbose_name='просмотры за день')),
                ('views_week', models.IntegerField(default=0, verbose_name='просмотры за неделю')),
                ('views_month', models.IntegerField(default=0, verbose_name='просмотры за месяц')),
                ('views_quarter', models.IntegerField(default=0, verbose_name='просмотры за квартал')),
                ('is_username', models.BooleanField(default=False)),
                ('rating', models.IntegerField(default=0, verbose_name='рейтинг')),
                ('last_message', models.TextField(default='')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='channels.niche', verbose_name='Категория')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.client', verbose_name='Владелец')),
                ('rewards', models.ManyToManyField(to='users.Reward')),
            ],
            options={
                'verbose_name': 'Канал пользователя',
                'verbose_name_plural': 'Канал пользователя',
                'ordering': ['rating'],
            },
        ),
    ]
