# Generated by Django 3.1.4 on 2022-04-26 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0008_account_niche'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='last_message',
        ),
    ]
