# Generated by Django 3.1.4 on 2022-04-27 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_client_subscription'),
        ('channels', '0009_remove_account_last_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='rewards',
            field=models.ManyToManyField(blank=True, default=None, to='users.Reward'),
        ),
    ]
