# Generated by Django 3.1.4 on 2022-05-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0014_auto_20220505_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='banner_url',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Аватарка канала'),
        ),
        migrations.AddField(
            model_name='account',
            name='channel_country',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Страна канала'),
        ),
        migrations.AddField(
            model_name='account',
            name='channel_keywords',
            field=models.TextField(blank=True, null=True, verbose_name='Указанные ключевые слова'),
        ),
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок канала'),
        ),
    ]
