# Generated by Django 3.1.7 on 2021-03-01 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_auto_20210301_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='category',
        ),
    ]
