# Generated by Django 3.1.7 on 2021-03-09 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_completetask_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='completetask',
            name='status',
            field=models.CharField(choices=[('CH', 'Задание на проверке'), ('CM', 'Задание выполнено'), ('FL', 'Задание провалено')], default='CH', max_length=2),
        ),
        migrations.AddField(
            model_name='question',
            name='task_rating',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='user',
            name='is_username',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
