# Generated by Django 3.1.7 on 2021-03-09 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_auto_20210309_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='youtube',
            field=models.CharField(max_length=200),
        ),
    ]
