# Generated by Django 3.1.7 on 2021-03-11 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_auto_20210309_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='task_rating',
        ),
        migrations.AddField(
            model_name='task',
            name='task_rating',
            field=models.IntegerField(default=2),
        ),
    ]
