# Generated by Django 3.1.7 on 2021-03-14 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0020_user_registration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subs_day',
            field=models.IntegerField(default=0, verbose_name='изменение количества подписчиков за день'),
        ),
        migrations.AddField(
            model_name='user',
            name='subs_month',
            field=models.IntegerField(default=0, verbose_name='изменение количества подписчиков за месяц'),
        ),
        migrations.AddField(
            model_name='user',
            name='subs_quarter',
            field=models.IntegerField(default=0, verbose_name='изменение количества подписчиков за квартал'),
        ),
        migrations.AddField(
            model_name='user',
            name='subs_week',
            field=models.IntegerField(default=0, verbose_name='изменение количества подписчиков за неделю'),
        ),
        migrations.AddField(
            model_name='user',
            name='views_day',
            field=models.IntegerField(default=0, verbose_name='изменение количества просмотров за день'),
        ),
        migrations.AddField(
            model_name='user',
            name='views_month',
            field=models.IntegerField(default=0, verbose_name='изменение количества просмотров за месяц'),
        ),
        migrations.AddField(
            model_name='user',
            name='views_quarter',
            field=models.IntegerField(default=0, verbose_name='изменение количества просмотров за квартал'),
        ),
        migrations.AddField(
            model_name='user',
            name='views_week',
            field=models.IntegerField(default=0, verbose_name='изменение количества просмотров за неделю'),
        ),
    ]
