# Generated by Django 3.1.7 on 2021-03-14 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0021_auto_20210314_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subs_day',
            field=models.IntegerField(default=0, verbose_name='подписчики за день'),
        ),
        migrations.AlterField(
            model_name='user',
            name='subs_month',
            field=models.IntegerField(default=0, verbose_name='подписчики за месяц'),
        ),
        migrations.AlterField(
            model_name='user',
            name='subs_quarter',
            field=models.IntegerField(default=0, verbose_name='подписчики за квартал'),
        ),
        migrations.AlterField(
            model_name='user',
            name='subs_week',
            field=models.IntegerField(default=0, verbose_name='подписчики за неделю'),
        ),
        migrations.AlterField(
            model_name='user',
            name='views_day',
            field=models.IntegerField(default=0, verbose_name='просмотры за день'),
        ),
        migrations.AlterField(
            model_name='user',
            name='views_month',
            field=models.IntegerField(default=0, verbose_name='просмотры за месяц'),
        ),
        migrations.AlterField(
            model_name='user',
            name='views_quarter',
            field=models.IntegerField(default=0, verbose_name='просмотры за квартал'),
        ),
        migrations.AlterField(
            model_name='user',
            name='views_week',
            field=models.IntegerField(default=0, verbose_name='просмотры за неделю'),
        ),
    ]
