# Generated by Django 3.1.7 on 2021-03-23 15:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0023_usertime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertime',
            name='user',
        ),
        migrations.AddField(
            model_name='usertime',
            name='chat',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='usertime',
            name='time_from_last_message',
            field=models.TimeField(default=datetime.datetime(2021, 3, 23, 18, 30, 27, 248113)),
        ),
    ]
