# Generated by Django 3.1.7 on 2021-12-30 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0026_auto_20211030_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='chat',
            field=models.IntegerField(default=0, verbose_name='идентификатор чата'),
        ),
        migrations.AlterField(
            model_name='usertime',
            name='time_from_last_message',
            field=models.TimeField(default=datetime.datetime(2021, 12, 30, 17, 19, 44, 375791)),
        ),
    ]
