# Generated by Django 3.1.4 on 2022-04-26 19:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0027_auto_20211230_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertime',
            name='time_from_last_message',
            field=models.TimeField(default=datetime.datetime(2022, 4, 26, 22, 43, 38, 175174)),
        ),
    ]
