# Generated by Django 3.1.4 on 2022-05-01 13:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0058_auto_20220428_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertime',
            name='time_from_last_message',
            field=models.TimeField(default=datetime.datetime(2022, 5, 1, 16, 5, 15, 145345)),
        ),
    ]
