# Generated by Django 3.1.4 on 2022-05-04 16:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0059_auto_20220501_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertime',
            name='time_from_last_message',
            field=models.TimeField(default=datetime.datetime(2022, 5, 4, 19, 54, 9, 576414)),
        ),
    ]
