# Generated by Django 3.1.4 on 2022-05-04 18:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0060_auto_20220504_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertime',
            name='time_from_last_message',
            field=models.TimeField(default=datetime.datetime(2022, 5, 4, 21, 13, 32, 51053)),
        ),
    ]
