# Generated by Django 3.1.4 on 2022-05-04 23:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0062_auto_20220504_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertime',
            name='time_from_last_message',
            field=models.TimeField(default=datetime.datetime(2022, 5, 5, 2, 39, 26, 2233)),
        ),
    ]
