# Generated by Django 3.1.4 on 2022-05-06 15:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0063_auto_20220505_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertime',
            name='time_from_last_message',
            field=models.TimeField(default=datetime.datetime(2022, 5, 6, 18, 2, 21, 80107)),
        ),
    ]
